
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayank
 */
public class Decode_screen extends javax.swing.JFrame {

    /**
     * Creates new form Decode_screen
     */
    int user_id;
    String path;
    int cnt=0;
    public Decode_screen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Decode_screen(int user_id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user_id = user_id;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encode2 = new javax.swing.JLabel();
        encode1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        encode3 = new javax.swing.JLabel();
        PhotoLabel = new javax.swing.JLabel();
        encode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1320, 720));
        setMinimumSize(new java.awt.Dimension(1320, 720));
        setPreferredSize(new java.awt.Dimension(1320, 720));
        getContentPane().setLayout(null);

        encode2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        encode2.setForeground(new java.awt.Color(255, 255, 255));
        encode2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encode2.setText("View Recent Images");
        encode2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));
        encode2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encode2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encode2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encode2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encode2MouseExited(evt);
            }
        });
        getContentPane().add(encode2);
        encode2.setBounds(190, 520, 390, 50);

        encode1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        encode1.setForeground(new java.awt.Color(102, 255, 51));
        encode1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encode1.setText("Decode");
        encode1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encode1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encode1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encode1MouseExited(evt);
            }
        });
        getContentPane().add(encode1);
        encode1.setBounds(500, 50, 300, 50);

        jSeparator2.setBackground(new java.awt.Color(102, 255, 51));
        jSeparator2.setForeground(new java.awt.Color(102, 255, 51));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(400, 110, 510, 30);

        jSeparator3.setBackground(new java.awt.Color(102, 255, 51));
        jSeparator3.setForeground(new java.awt.Color(102, 255, 51));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(400, 40, 510, 30);

        encode3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        encode3.setForeground(new java.awt.Color(255, 255, 255));
        encode3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encode3.setText("Select from Device");
        encode3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));
        encode3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encode3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encode3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encode3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encode3MouseExited(evt);
            }
        });
        getContentPane().add(encode3);
        encode3.setBounds(690, 520, 360, 50);
        getContentPane().add(PhotoLabel);
        PhotoLabel.setBounds(430, 140, 450, 340);

        encode.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        encode.setForeground(new java.awt.Color(255, 255, 255));
        encode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encode.setText("Decode");
        encode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));
        encode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encodeMouseExited(evt);
            }
        });
        getContentPane().add(encode);
        encode.setBounds(460, 610, 360, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/left-arrow.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 40, 70, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1320, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encode2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode2MouseEntered
        // TODO add your handling code here:
        encode2.setForeground(Color.GREEN);
        Color VISIBLE_BORDER     = new java.awt.Color(255,255,255); 
        LineBorder visibleBorder     = new LineBorder( VISIBLE_BORDER,     1); 
        
        encode2.setBorder(visibleBorder);
        
    }//GEN-LAST:event_encode2MouseEntered

    private void encode2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode2MouseExited
        // TODO add your handling code here:
        encode2.setForeground(Color.WHITE);
        Color VISIBLE_BORDER     = new java.awt.Color(102,255,51); 
        LineBorder visibleBorder     = new LineBorder( VISIBLE_BORDER,     1); 
        
        encode2.setBorder(visibleBorder);
        
    }//GEN-LAST:event_encode2MouseExited

    private void encode1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode1MouseEntered
        // TODO add your handling code here:
        encode1.setForeground(Color.WHITE);
    }//GEN-LAST:event_encode1MouseEntered

    private void encode1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode1MouseExited
        // TODO add your handling code here:
        encode1.setForeground(Color.GREEN);
    }//GEN-LAST:event_encode1MouseExited

    private void encode3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode3MouseEntered
        // TODO add your handling code here:
        encode3.setForeground(Color.GREEN);
        Color VISIBLE_BORDER     = new java.awt.Color(255,255,255); 
        LineBorder visibleBorder     = new LineBorder( VISIBLE_BORDER,     1); 
        
        encode3.setBorder(visibleBorder);
        
    }//GEN-LAST:event_encode3MouseEntered

    private void encode3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode3MouseExited
        // TODO add your handling code here:
        encode3.setForeground(Color.WHITE);
        Color VISIBLE_BORDER     = new java.awt.Color(102,255,51); 
        LineBorder visibleBorder     = new LineBorder( VISIBLE_BORDER,     1); 
        
        encode3.setBorder(visibleBorder);
        
    }//GEN-LAST:event_encode3MouseExited

    private void encodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encodeMouseEntered
        // TODO add your handling code here:
        encode.setForeground(Color.GREEN);
        Color VISIBLE_BORDER     = new java.awt.Color(255,255,255);
        LineBorder visibleBorder     = new LineBorder( VISIBLE_BORDER,     1);

        encode.setBorder(visibleBorder);
    }//GEN-LAST:event_encodeMouseEntered

    private void encodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encodeMouseExited
        // TODO add your handling code here:
        encode.setForeground(Color.WHITE);
        Color VISIBLE_BORDER     = new java.awt.Color(102,255,51);
        LineBorder visibleBorder     = new LineBorder( VISIBLE_BORDER,     1);

        encode.setBorder(visibleBorder);
    }//GEN-LAST:event_encodeMouseExited

    private void encode3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode3MouseClicked
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        //file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "png", "jpeg");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);

        path = null;
        File selectedFile = null;
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();

            ImageIcon MyImage = new ImageIcon(path);
            Image img = MyImage.getImage();
            Image newImage = img.getScaledInstance(PhotoLabel.getWidth(), PhotoLabel.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon image = new ImageIcon(newImage);
            PhotoLabel.setIcon(image);
            cnt++;
            
        }
    }//GEN-LAST:event_encode3MouseClicked

    private void encodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encodeMouseClicked
        // TODO add your handling code here:
        if(cnt==0)
        {
            JOptionPane.showMessageDialog(this, "Image is not selected !", "ERROR !", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Decode_2 d2 = new Decode_2(user_id,path);
            this.setVisible(false);
            d2.setVisible(true);
        }
    }//GEN-LAST:event_encodeMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Encode_decode ee = new Encode_decode(user_id);
        this.setVisible(false);
        ee.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void encode2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode2MouseClicked
        // TODO add your handling code here:
        Recently r = new Recently(user_id);
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_encode2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Decode_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Decode_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Decode_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Decode_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Decode_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PhotoLabel;
    private javax.swing.JLabel encode;
    private javax.swing.JLabel encode1;
    private javax.swing.JLabel encode2;
    private javax.swing.JLabel encode3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
