
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javafx.scene.layout.Border;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Mayank
 */
public class Login_Register extends javax.swing.JFrame {

    /**
     * Creates new form Login_Register
     */
    private Connection conn, conn1;
    private Statement stmt, stmt1;
    private ResultSet rs;
    public int userid;

    public Login_Register() {
        initComponents();
        this.setBackground(Color.red);
        this.setLocationRelativeTo(null);
        EmailLoginTF.setBackground(new Color(0, 0, 0, 0));
        PasswordLogin.setBackground(new Color(0, 0, 0, 0));
        jLabel22.setBackground(new Color(0, 0, 0, 0));
        EmailTF.setBackground(new Color(0, 0, 0, 0));
        UsernameTF.setBackground(new Color(0, 0, 0, 0));
        PasswordTF.setBackground(new Color(0, 0, 0, 0));
        ConfirmPasswordTF.setBackground(new Color(0, 0, 0, 0));
        passcon.setBackground(new Color(0, 0, 0, 0));
        passcon1.setBackground(new Color(0, 0, 0, 0));
        jLabel23.setBackground(new Color(0, 0, 0, 0));
        EmailTF1.setBackground(new Color(0, 0, 0, 0));
        signup.setVisible(false);
        ForgetPassword.setVisible(false);
        login.setVisible(true);
        login.setLocation(550, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        EmailLoginTF = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PasswordLogin = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        signup = new javax.swing.JPanel();
        jSeparator7 = new javax.swing.JSeparator();
        ConfirmPasswordTF = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        EmailTF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        PasswordTF = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        UsernameTF = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        ForgetPassword = new javax.swing.JPanel();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        passcon = new javax.swing.JPasswordField();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        passcon1 = new javax.swing.JPasswordField();
        EmailTF1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        register = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1320, 699));
        setMinimumSize(new java.awt.Dimension(1320, 699));
        setPreferredSize(new java.awt.Dimension(1320, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        login.setMaximumSize(new java.awt.Dimension(720, 699));
        login.setMinimumSize(new java.awt.Dimension(720, 699));
        login.setOpaque(false);
        login.setLayout(null);

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SIGN IN");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        login.add(jLabel15);
        jLabel15.setBounds(260, 70, 210, 46);

        jSeparator13.setForeground(new java.awt.Color(51, 255, 204));
        login.add(jSeparator13);
        jSeparator13.setBounds(130, 160, 500, 40);

        jSeparator14.setForeground(new java.awt.Color(51, 255, 204));
        login.add(jSeparator14);
        jSeparator14.setBounds(130, 520, 500, 40);

        EmailLoginTF.setBackground(new java.awt.Color(51, 51, 51));
        EmailLoginTF.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        EmailLoginTF.setForeground(new java.awt.Color(51, 255, 51));
        EmailLoginTF.setBorder(null);
        EmailLoginTF.setCaretColor(new java.awt.Color(255, 255, 0));
        EmailLoginTF.setOpaque(false);
        login.add(EmailLoginTF);
        EmailLoginTF.setBounds(160, 270, 420, 30);

        jSeparator17.setForeground(new java.awt.Color(255, 255, 255));
        login.add(jSeparator17);
        jSeparator17.setBounds(160, 300, 420, 30);

        jSeparator18.setForeground(new java.awt.Color(255, 255, 255));
        login.add(jSeparator18);
        jSeparator18.setBounds(160, 410, 420, 20);

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Login");
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        login.add(jLabel18);
        jLabel18.setBounds(130, 570, 500, 46);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Forgot password ?");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        login.add(jLabel4);
        jLabel4.setBounds(160, 460, 420, 30);

        jLabel17.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel17.setForeground(java.awt.SystemColor.control);
        jLabel17.setText("Password");
        login.add(jLabel17);
        jLabel17.setBounds(160, 340, 130, 30);

        PasswordLogin.setBackground(new java.awt.Color(51, 51, 51));
        PasswordLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PasswordLogin.setForeground(new java.awt.Color(51, 255, 51));
        PasswordLogin.setBorder(null);
        PasswordLogin.setCaretColor(new java.awt.Color(255, 255, 0));
        PasswordLogin.setOpaque(false);
        PasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordLoginActionPerformed(evt);
            }
        });
        login.add(PasswordLogin);
        PasswordLogin.setBounds(160, 380, 420, 30);

        jLabel16.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel16.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel16.setForeground(java.awt.SystemColor.control);
        jLabel16.setText("Email Id");
        login.add(jLabel16);
        jLabel16.setBounds(160, 230, 110, 30);

        getContentPane().add(login);
        login.setBounds(0, 0, 720, 720);

        signup.setMaximumSize(new java.awt.Dimension(770, 699));
        signup.setMinimumSize(new java.awt.Dimension(770, 699));
        signup.setOpaque(false);
        signup.setPreferredSize(new java.awt.Dimension(770, 720));
        signup.setLayout(null);

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        signup.add(jSeparator7);
        jSeparator7.setBounds(170, 480, 420, 20);

        ConfirmPasswordTF.setBackground(new java.awt.Color(51, 51, 51));
        ConfirmPasswordTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ConfirmPasswordTF.setForeground(new java.awt.Color(255, 255, 0));
        ConfirmPasswordTF.setBorder(null);
        ConfirmPasswordTF.setCaretColor(new java.awt.Color(255, 255, 0));
        ConfirmPasswordTF.setOpaque(false);
        ConfirmPasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordTFActionPerformed(evt);
            }
        });
        signup.add(ConfirmPasswordTF);
        ConfirmPasswordTF.setBounds(170, 450, 420, 30);

        jLabel2.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel2.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.control);
        jLabel2.setText("Confirm Password");
        signup.add(jLabel2);
        jLabel2.setBounds(170, 410, 218, 30);

        jLabel5.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.SystemColor.control);
        jLabel5.setText("Username");
        signup.add(jLabel5);
        jLabel5.setBounds(170, 140, 149, 30);

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        signup.add(jSeparator6);
        jSeparator6.setBounds(166, 392, 420, 2);

        jLabel7.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.control);
        jLabel7.setText("Password");
        signup.add(jLabel7);
        jLabel7.setBounds(170, 320, 149, 30);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Already have an account ?");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        signup.add(jLabel12);
        jLabel12.setBounds(250, 640, 270, 40);

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Register");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        signup.add(jLabel11);
        jLabel11.setBounds(260, 30, 230, 40);

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        signup.add(jSeparator5);
        jSeparator5.setBounds(170, 300, 420, 10);

        EmailTF.setBackground(new java.awt.Color(51, 51, 51));
        EmailTF.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        EmailTF.setForeground(new java.awt.Color(255, 255, 0));
        EmailTF.setBorder(null);
        EmailTF.setCaretColor(new java.awt.Color(255, 255, 0));
        EmailTF.setOpaque(false);
        EmailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTFActionPerformed(evt);
            }
        });
        signup.add(EmailTF);
        EmailTF.setBounds(170, 270, 420, 30);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        signup.add(jSeparator2);
        jSeparator2.setBounds(170, 210, 420, 30);

        PasswordTF.setBackground(new java.awt.Color(51, 51, 51));
        PasswordTF.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PasswordTF.setForeground(new java.awt.Color(255, 255, 0));
        PasswordTF.setBorder(null);
        PasswordTF.setCaretColor(new java.awt.Color(255, 255, 0));
        PasswordTF.setOpaque(false);
        signup.add(PasswordTF);
        PasswordTF.setBounds(170, 360, 420, 30);

        jLabel6.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.control);
        jLabel6.setText("Email");
        signup.add(jLabel6);
        jLabel6.setBounds(170, 230, 149, 30);

        UsernameTF.setBackground(new java.awt.Color(51, 51, 51));
        UsernameTF.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        UsernameTF.setForeground(new java.awt.Color(255, 255, 0));
        UsernameTF.setBorder(null);
        UsernameTF.setCaretColor(new java.awt.Color(255, 255, 0));
        UsernameTF.setOpaque(false);
        UsernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTFActionPerformed(evt);
            }
        });
        signup.add(UsernameTF);
        UsernameTF.setBounds(170, 180, 420, 30);

        jSeparator15.setForeground(new java.awt.Color(51, 255, 204));
        signup.add(jSeparator15);
        jSeparator15.setBounds(140, 100, 500, 40);

        jSeparator16.setForeground(new java.awt.Color(51, 255, 204));
        signup.add(jSeparator16);
        jSeparator16.setBounds(140, 520, 500, 40);

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Sign Up");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        signup.add(jLabel22);
        jLabel22.setBounds(130, 570, 500, 46);

        getContentPane().add(signup);
        signup.setBounds(0, 0, 770, 720);

        ForgetPassword.setOpaque(false);
        ForgetPassword.setLayout(null);

        jSeparator20.setForeground(new java.awt.Color(51, 255, 204));
        ForgetPassword.add(jSeparator20);
        jSeparator20.setBounds(130, 550, 500, 40);

        jSeparator19.setForeground(new java.awt.Color(51, 255, 204));
        ForgetPassword.add(jSeparator19);
        jSeparator19.setBounds(130, 130, 500, 30);

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Change Password");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        ForgetPassword.add(jLabel20);
        jLabel20.setBounds(200, 50, 350, 46);

        jLabel19.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel19.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel19.setForeground(java.awt.SystemColor.control);
        jLabel19.setText("New Password");
        ForgetPassword.add(jLabel19);
        jLabel19.setBounds(190, 300, 210, 30);

        jLabel21.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel21.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel21.setForeground(java.awt.SystemColor.control);
        jLabel21.setText("Confirm Password");
        ForgetPassword.add(jLabel21);
        jLabel21.setBounds(190, 410, 270, 30);

        passcon.setBackground(new java.awt.Color(51, 51, 51));
        passcon.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        passcon.setForeground(new java.awt.Color(51, 255, 51));
        passcon.setBorder(null);
        passcon.setCaretColor(new java.awt.Color(255, 255, 0));
        passcon.setOpaque(false);
        ForgetPassword.add(passcon);
        passcon.setBounds(190, 340, 420, 30);

        jSeparator21.setForeground(new java.awt.Color(255, 255, 255));
        ForgetPassword.add(jSeparator21);
        jSeparator21.setBounds(190, 370, 420, 30);

        jSeparator22.setForeground(new java.awt.Color(255, 255, 255));
        ForgetPassword.add(jSeparator22);
        jSeparator22.setBounds(190, 480, 420, 20);

        passcon1.setBackground(new java.awt.Color(51, 51, 51));
        passcon1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        passcon1.setForeground(new java.awt.Color(51, 255, 51));
        passcon1.setBorder(null);
        passcon1.setCaretColor(new java.awt.Color(255, 255, 0));
        passcon1.setOpaque(false);
        ForgetPassword.add(passcon1);
        passcon1.setBounds(190, 450, 420, 30);

        EmailTF1.setBackground(new java.awt.Color(51, 51, 51));
        EmailTF1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        EmailTF1.setForeground(new java.awt.Color(51, 255, 51));
        EmailTF1.setBorder(null);
        EmailTF1.setCaretColor(new java.awt.Color(255, 255, 0));
        EmailTF1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        EmailTF1.setOpaque(false);
        EmailTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTF1ActionPerformed(evt);
            }
        });
        ForgetPassword.add(EmailTF1);
        EmailTF1.setBounds(190, 230, 420, 30);

        jLabel8.setBackground(java.awt.SystemColor.activeCaptionText);
        jLabel8.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.control);
        jLabel8.setText("Email");
        ForgetPassword.add(jLabel8);
        jLabel8.setBounds(190, 190, 149, 30);

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        ForgetPassword.add(jSeparator8);
        jSeparator8.setBounds(190, 260, 420, 10);

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Update Password");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        ForgetPassword.add(jLabel23);
        jLabel23.setBounds(130, 610, 500, 46);

        getContentPane().add(ForgetPassword);
        ForgetPassword.setBounds(550, 0, 770, 720);

        register.setBackground(new java.awt.Color(11, 12, 12));
        register.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Register");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        register.add(jLabel10);
        jLabel10.setBounds(80, 600, 410, 46);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Annotation 2019-11-10 155948.png"))); // NOI18N
        register.add(jLabel3);
        jLabel3.setBounds(50, 110, 480, 370);

        getContentPane().add(register);
        register.setBounds(0, 0, 550, 720);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1320, 720));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1320, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        jLabel10.setForeground(Color.GREEN);
        Color VISIBLE_BORDER = new java.awt.Color(255, 255, 255);
        LineBorder visibleBorder = new LineBorder(VISIBLE_BORDER, 1);

        jLabel10.setBorder(visibleBorder);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        jLabel10.setForeground(Color.WHITE);
        Color VISIBLE_BORDER = new java.awt.Color(102, 255, 51);
        LineBorder visibleBorder = new LineBorder(VISIBLE_BORDER, 1);

        jLabel10.setBorder(visibleBorder);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseExited

    private void ConfirmPasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordTFActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        login.setVisible(true);
        signup.setVisible(false);
        login.setLocation(550, 0);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void EmailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTFActionPerformed

    private void UsernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTFActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        login.setVisible(false);
        ForgetPassword.setVisible(false);
        signup.setVisible(true);
        signup.setLocation(550, 0);

    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        login.setVisible(false);
        ForgetPassword.setVisible(true);
        ForgetPassword.setLocation(550, 0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
        jLabel18.setForeground(Color.WHITE);
        Color VISIBLE_BORDER = new java.awt.Color(102, 255, 51);
        LineBorder visibleBorder = new LineBorder(VISIBLE_BORDER, 1);

        jLabel18.setBorder(visibleBorder);
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
        jLabel18.setForeground(Color.GREEN);
        Color VISIBLE_BORDER = new java.awt.Color(255, 255, 255);
        LineBorder visibleBorder = new LineBorder(VISIBLE_BORDER, 1);

        jLabel18.setBorder(visibleBorder);
    }//GEN-LAST:event_jLabel18MouseEntered

    private void EmailTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTF1ActionPerformed

    private void PasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordLoginActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        // i am here....
        String email = EmailLoginTF.getText();
        String loginpwd = PasswordLogin.getText();
        if (loginpwd.length() == 0) {
            JOptionPane.showMessageDialog(this, "Password fields shouldn't be blank.", "ERROR !", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if ((!(email.contains("@") && email.contains("."))) || (email.contains("'") || email.contains("_") || email.contains("(") || email.contains("+") || email.contains("-") || email.contains("*") || email.contains("/") || email.contains("~") || email.contains("!") || email.contains("#") || email.contains("$") || email.contains("%") || email.contains("^") || email.contains("&") || email.contains(")"))) {
                JOptionPane.showMessageDialog(this, "Given email-id isn't valid !", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            } else if (loginpwd.length() < 6) {
                JOptionPane.showMessageDialog(this, "Password should be atleast 6 characters long.", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {

                    Class.forName("com.mysql.jdbc.Driver");

                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stegofi", "root", "mayank");

                    stmt = conn.createStatement();

                    rs = stmt.executeQuery("SELECT * FROM `register` WHERE Email='" + EmailLoginTF.getText() + "' AND Password='" + PasswordLogin.getText() + "';");

                    if (rs.next() == true) {

                        JOptionPane.showMessageDialog(this, "Successfully Logged...!", "Success", JOptionPane.INFORMATION_MESSAGE);
                        EmailLoginTF.setText("");
                        PasswordLogin.setText("");

                        Encode_decode c = new Encode_decode(rs.getInt("UserId"));
                        this.setVisible(false);
                        c.setVisible(true);
                    } else if (rs.next() == false) {
                        JOptionPane.showMessageDialog(this, "Something went wrong...", "ERROR !", JOptionPane.ERROR_MESSAGE);
                        PasswordLogin.setText("");
                    }
                    conn.close();

                } catch (Exception e) {

                    System.out.println(e);

                }
            }
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
        String uname = UsernameTF.getText();
        String email = EmailTF.getText();
        String Pass = PasswordTF.getText();
        String CPass = ConfirmPasswordTF.getText();
        if (Pass.length() == 0 && CPass.length() == 0) {
            JOptionPane.showMessageDialog(this, "Password fields shouldn't be blank.", "ERROR !", JOptionPane.INFORMATION_MESSAGE);
        }
        if (Pass.equals(CPass) && Pass.length() != 0 && CPass.length() != 0) {
            if (uname.length() < 3) {
                JOptionPane.showMessageDialog(this, "Username must be atleast 3 chracters.", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            } else if ((!(email.contains("@") && email.contains("."))) || (email.contains("'") || email.contains("_") || email.contains("(") || email.contains("+") || email.contains("-") || email.contains("*") || email.contains("/") || email.contains("~") || email.contains("!") || email.contains("#") || email.contains("$") || email.contains("%") || email.contains("^") || email.contains("&") || email.contains(")"))) {
                JOptionPane.showMessageDialog(this, "Given email-id isn't valid !", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            } else if (Pass.length() < 6) {
                JOptionPane.showMessageDialog(this, "Password should be atleast 6 characters long.", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {

                    Class.forName("com.mysql.jdbc.Driver");

                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stegofi", "root", "mayank");

                    stmt = conn.createStatement();

                    rs = stmt.executeQuery("SELECT `Email` FROM `register` WHERE Email='" + email + "';");

                    if (rs.next() == true) {

                        JOptionPane.showMessageDialog(this, "Email-ID already exist.", "ERROR !", JOptionPane.ERROR_MESSAGE);
                    } else if (rs.next() == false) {
                        try {
                            stmt.executeUpdate("INSERT INTO `register`(`UserId`, `Username`, `Email`, `Password`) VALUES (NULL,'" + uname + "','" + email + "','" + Pass + "');");
                            JOptionPane.showMessageDialog(this, "Successfully Registered...", "Success", JOptionPane.INFORMATION_MESSAGE);
                            signup.setVisible(false);
                            login.setVisible(true);
                            login.setLocation(550, 0);
                        } catch (Exception e) {
                            //JOptionPane.showMessageDialog(this, "Email-ID already whyexist.", "ERROR !", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    conn.close();

                } catch (Exception e) {

                    System.out.println(e);

                }
            }
        } else if (Pass.length() != 0 && CPass.length() != 0) {
            JOptionPane.showMessageDialog(this, "Password and Confirm Password aren't matched.", "ERROR...!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        // TODO add your handling code here:
        jLabel22.setForeground(Color.GREEN);
        Color VISIBLE_BORDER = new java.awt.Color(255, 255, 255);
        LineBorder visibleBorder = new LineBorder(VISIBLE_BORDER, 1);

        jLabel22.setBorder(visibleBorder);
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        // TODO add your handling code here:
        jLabel22.setForeground(Color.WHITE);
        Color VISIBLE_BORDER = new java.awt.Color(102, 255, 51);
        LineBorder visibleBorder = new LineBorder(VISIBLE_BORDER, 1);

        jLabel22.setBorder(visibleBorder);
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        String pwd = passcon.getText();
        String confirmpwd = passcon1.getText();
        if (pwd.length() == 0 && confirmpwd.length() == 0) {
            JOptionPane.showMessageDialog(this, "Password fields shouldn't be blank.", "ERROR !", JOptionPane.INFORMATION_MESSAGE);
        } else if (pwd.equals(confirmpwd) && pwd.length() != 0 && confirmpwd.length() != 0) {
            if (pwd.length() < 6) {
                JOptionPane.showMessageDialog(this, "Password should be atleast 6 characters long.", "NOTICE", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {

                    Class.forName("com.mysql.jdbc.Driver");

                    conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/stegofi", "root", "mayank");

                    stmt = conn.createStatement();

                    int result = stmt.executeUpdate("UPDATE `register` SET `Password`= '" + pwd + "' WHERE Email = '" + EmailTF1.getText() + "';");

                    if (result == 1) {
                        JOptionPane.showMessageDialog(this, "Your Password changed successfully !", "Change Password", JOptionPane.INFORMATION_MESSAGE);
                        ForgetPassword.setVisible(false);
                        login.setVisible(true);
                        login.setLocation(550, 0);

                    } else {
                        JOptionPane.showMessageDialog(this, "ERROR ocurred...! Please try again.", "Change Password", JOptionPane.INFORMATION_MESSAGE);
                    }

                    conn.close();

                } catch (Exception e) {

                    System.out.println(e);

                }
            }

        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
        // TODO add your handling code here:
        jLabel23.setForeground(Color.GREEN);
        Color VISIBLE_BORDER = new java.awt.Color(255, 255, 255);
        LineBorder visibleBorder = new LineBorder(VISIBLE_BORDER, 1);

        jLabel23.setBorder(visibleBorder);
    }//GEN-LAST:event_jLabel23MouseEntered

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        // TODO add your handling code here:
        jLabel23.setForeground(Color.WHITE);
        Color VISIBLE_BORDER = new java.awt.Color(102, 255, 51);
        LineBorder visibleBorder = new LineBorder(VISIBLE_BORDER, 1);

        jLabel23.setBorder(visibleBorder);
    }//GEN-LAST:event_jLabel23MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPasswordTF;
    private javax.swing.JTextField EmailLoginTF;
    private javax.swing.JTextField EmailTF;
    private javax.swing.JTextField EmailTF1;
    private javax.swing.JPanel ForgetPassword;
    private javax.swing.JPasswordField PasswordLogin;
    private javax.swing.JPasswordField PasswordTF;
    private javax.swing.JTextField UsernameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel login;
    private javax.swing.JPasswordField passcon;
    private javax.swing.JPasswordField passcon1;
    private javax.swing.JPanel register;
    private javax.swing.JPanel signup;
    // End of variables declaration//GEN-END:variables
}
