
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.border.LineBorder;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mayank
 */
public class Share_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Share_Screen
     */
    public Share_Screen() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    int cnt=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        encode1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        PhotoLabel = new javax.swing.JLabel();
        encode2 = new javax.swing.JLabel();
        encode3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1320, 720));
        setMinimumSize(new java.awt.Dimension(1320, 720));
        setPreferredSize(new java.awt.Dimension(1320, 720));
        getContentPane().setLayout(null);

        encode1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        encode1.setForeground(new java.awt.Color(102, 255, 51));
        encode1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encode1.setText("Encode");
        encode1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encode1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encode1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encode1MouseExited(evt);
            }
        });
        getContentPane().add(encode1);
        encode1.setBounds(500, 50, 300, 50);

        jSeparator3.setBackground(new java.awt.Color(102, 255, 51));
        jSeparator3.setForeground(new java.awt.Color(102, 255, 51));
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(400, 40, 510, 30);

        jSeparator2.setBackground(new java.awt.Color(102, 255, 51));
        jSeparator2.setForeground(new java.awt.Color(102, 255, 51));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(400, 110, 510, 30);
        getContentPane().add(PhotoLabel);
        PhotoLabel.setBounds(430, 160, 450, 340);

        encode2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        encode2.setForeground(new java.awt.Color(255, 255, 255));
        encode2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encode2.setText("Send a Mail");
        encode2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));
        encode2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encode2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encode2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encode2MouseExited(evt);
            }
        });
        getContentPane().add(encode2);
        encode2.setBounds(180, 590, 390, 50);

        encode3.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        encode3.setForeground(new java.awt.Color(255, 255, 255));
        encode3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encode3.setText("Save to Device");
        encode3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 51)));
        encode3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        encode3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encode3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                encode3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                encode3MouseExited(evt);
            }
        });
        getContentPane().add(encode3);
        encode3.setBounds(690, 590, 360, 50);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lightbulb.png"))); // NOI18N
        jLabel2.setText("Image shown above is data hided image.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 670, 1150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1320, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encode1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode1MouseEntered
        // TODO add your handling code here:
        encode1.setForeground(Color.WHITE);
    }//GEN-LAST:event_encode1MouseEntered

    private void encode1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode1MouseExited
        // TODO add your handling code here:
        encode1.setForeground(Color.GREEN);
    }//GEN-LAST:event_encode1MouseExited

    private void encode2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode2MouseEntered
        // TODO add your handling code here:
        encode2.setForeground(Color.GREEN);
        Color VISIBLE_BORDER     = new java.awt.Color(255,255,255);
        LineBorder visibleBorder     = new LineBorder( VISIBLE_BORDER,     1);

        encode2.setBorder(visibleBorder);

    }//GEN-LAST:event_encode2MouseEntered

    private void encode2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode2MouseExited
        // TODO add your handling code here:
        encode2.setForeground(Color.WHITE);
        Color VISIBLE_BORDER     = new java.awt.Color(102,255,51);
        LineBorder visibleBorder     = new LineBorder( VISIBLE_BORDER,     1);

        encode2.setBorder(visibleBorder);

    }//GEN-LAST:event_encode2MouseExited

    private void encode3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode3MouseClicked
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        //file.setCurrentDirectory(new File(System.getProperty("user.home")));

        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "png", "jpeg");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);

        String path = null;
        File selectedFile = null;
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();

            //ImageIcon MyImage = new ImageIcon(path);
            //Image img = MyImage.getImage();
            //Image newImage = img.getScaledInstance(PhotoLabel.getWidth(), PhotoLabel.getHeight(), Image.SCALE_SMOOTH);
            //ImageIcon image = new ImageIcon(newImage);
            //PhotoLabel.setIcon(image);
            cnt++;

        }
    }//GEN-LAST:event_encode3MouseClicked

    private void encode3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode3MouseEntered
        // TODO add your handling code here:
        encode3.setForeground(Color.GREEN);
        Color VISIBLE_BORDER     = new java.awt.Color(255,255,255);
        LineBorder visibleBorder     = new LineBorder( VISIBLE_BORDER,     1);

        encode3.setBorder(visibleBorder);

    }//GEN-LAST:event_encode3MouseEntered

    private void encode3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encode3MouseExited
        // TODO add your handling code here:
        encode3.setForeground(Color.WHITE);
        Color VISIBLE_BORDER     = new java.awt.Color(102,255,51);
        LineBorder visibleBorder     = new LineBorder( VISIBLE_BORDER,     1);

        encode3.setBorder(visibleBorder);

    }//GEN-LAST:event_encode3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Share_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Share_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Share_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Share_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Share_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PhotoLabel;
    private javax.swing.JLabel encode1;
    private javax.swing.JLabel encode2;
    private javax.swing.JLabel encode3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
